### Create a Budget
POST http://localhost:3000/budgets
Content-Type: application/json

{
  "month": 5,
  "year": 2024,
  "category": "664b45fcdb719c7d6790f94d",
  "amount": 500.00
}

### Retrieve All Budgets
GET http://localhost:3000/budgets

### Calculate Monthly Budget 
### Analyze and summarize the financial transactions and planned expenses for a specific month. 
GET http://localhost:3000/budgets/?month=5&year=2024
