### Retrieve All Categories
GET http://localhost:3000/categories

### Create a Category
POST http://localhost:3000/categories
Content-Type: application/json

{

  "name": "Personal Care",
  "budgetLimit":"500",
  "currentExpenses":""
 

}

