### Create a Category
POST http://localhost:3000/categories
Content-Type: application/json

{

  "name": "Groceries",
  "budgetLimit":"0",
  "currentExpenses":"1"
 

}

### Retrieve All Categories
GET http://localhost:3000/categories

