GET http://localhost:3000/planned-expenses

###

POST http://localhost:3000/planned-expenses
Content-Type: application/json

{
  "amount": 155.00,
  "date": "2024-06-15T00:00:00.000Z",
  "category": "Food",
  "description": "Monthly grocery shopping"
}
